[package]
name = "spoonfed_pekzep"
version = "0.1.0"
authors = ["jekto_vatimeliju <jekto.vatimeliju@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = "1.0.115"
serde_derive = "1.0.115"
askama = "0.10.3"
pekzep_syllable = "0.1.2"
linked-hash-map = "0.5.3"
partition_eithers = "0.1.0"
readonly = "0.1.6"
env_logger = "0.7.1"
log = "0.4.11"